language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test

<<<<<<< HEAD
env:
  global:
    - CC_TEST_REPORTER_ID=cbf1cb4e050d8d1e3206fd43d085d24fb0facfa060111a7754bf0fc1df6df826
=======

env:
  global:
    - CC_TEST_REPORTER_ID=cbf1cb4e050d8d1e3206fd43d085d24fb0facfa060111a7754bf0fc1df6df826

>>>>>>> 29d2cafa7be9494c12523928ff574a5068738b68

after_success:
- npm run coveralls
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT